(cl:defpackage deploy-srv
  (:use )
  (:export
   "CHECKFOR3DOBJECTS"
   "<CHECKFOR3DOBJECTS-REQUEST>"
   "CHECKFOR3DOBJECTS-REQUEST"
   "<CHECKFOR3DOBJECTS-RESPONSE>"
   "CHECKFOR3DOBJECTS-RESPONSE"
  ))

