// Generated by gencpp from file deploy/CheckFor3DObjectsRequest.msg
// DO NOT EDIT!


#ifndef DEPLOY_MESSAGE_CHECKFOR3DOBJECTSREQUEST_H
#define DEPLOY_MESSAGE_CHECKFOR3DOBJECTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>

namespace deploy
{
template <class ContainerAllocator>
struct CheckFor3DObjectsRequest_
{
  typedef CheckFor3DObjectsRequest_<ContainerAllocator> Type;

  CheckFor3DObjectsRequest_()
    : id(0)
    , pc2()  {
    }
  CheckFor3DObjectsRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , pc2(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pc2_type;
  _pc2_type pc2;





  typedef boost::shared_ptr< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckFor3DObjectsRequest_

typedef ::deploy::CheckFor3DObjectsRequest_<std::allocator<void> > CheckFor3DObjectsRequest;

typedef boost::shared_ptr< ::deploy::CheckFor3DObjectsRequest > CheckFor3DObjectsRequestPtr;
typedef boost::shared_ptr< ::deploy::CheckFor3DObjectsRequest const> CheckFor3DObjectsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator1> & lhs, const ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pc2 == rhs.pc2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator1> & lhs, const ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace deploy

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "623ff9fc1bb472fa705dcd5fd85658e1";
  }

  static const char* value(const ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x623ff9fc1bb472faULL;
  static const uint64_t static_value2 = 0x705dcd5fd85658e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deploy/CheckFor3DObjectsRequest";
  }

  static const char* value(const ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n"
"sensor_msgs/PointCloud2 pc2\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pc2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckFor3DObjectsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deploy::CheckFor3DObjectsRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "pc2: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.pc2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPLOY_MESSAGE_CHECKFOR3DOBJECTSREQUEST_H
