// Generated by gencpp from file deploy/CheckFor3DObjects.msg
// DO NOT EDIT!


#ifndef DEPLOY_MESSAGE_CHECKFOR3DOBJECTS_H
#define DEPLOY_MESSAGE_CHECKFOR3DOBJECTS_H

#include <ros/service_traits.h>


#include <deploy/CheckFor3DObjectsRequest.h>
#include <deploy/CheckFor3DObjectsResponse.h>


namespace deploy
{

struct CheckFor3DObjects
{

typedef CheckFor3DObjectsRequest Request;
typedef CheckFor3DObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckFor3DObjects
} // namespace deploy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deploy::CheckFor3DObjects > {
  static const char* value()
  {
    return "121b3f4d608b21c3413c103ca56ebd0a";
  }

  static const char* value(const ::deploy::CheckFor3DObjects&) { return value(); }
};

template<>
struct DataType< ::deploy::CheckFor3DObjects > {
  static const char* value()
  {
    return "deploy/CheckFor3DObjects";
  }

  static const char* value(const ::deploy::CheckFor3DObjects&) { return value(); }
};


// service_traits::MD5Sum< ::deploy::CheckFor3DObjectsRequest> should match
// service_traits::MD5Sum< ::deploy::CheckFor3DObjects >
template<>
struct MD5Sum< ::deploy::CheckFor3DObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deploy::CheckFor3DObjects >::value();
  }
  static const char* value(const ::deploy::CheckFor3DObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deploy::CheckFor3DObjectsRequest> should match
// service_traits::DataType< ::deploy::CheckFor3DObjects >
template<>
struct DataType< ::deploy::CheckFor3DObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::deploy::CheckFor3DObjects >::value();
  }
  static const char* value(const ::deploy::CheckFor3DObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deploy::CheckFor3DObjectsResponse> should match
// service_traits::MD5Sum< ::deploy::CheckFor3DObjects >
template<>
struct MD5Sum< ::deploy::CheckFor3DObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deploy::CheckFor3DObjects >::value();
  }
  static const char* value(const ::deploy::CheckFor3DObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deploy::CheckFor3DObjectsResponse> should match
// service_traits::DataType< ::deploy::CheckFor3DObjects >
template<>
struct DataType< ::deploy::CheckFor3DObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::deploy::CheckFor3DObjects >::value();
  }
  static const char* value(const ::deploy::CheckFor3DObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPLOY_MESSAGE_CHECKFOR3DOBJECTS_H
